version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ${{ secrets.NICKNAME_GITHUB }}/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media/
  frontend:
    image: ${{ secrets.NICKNAME_GITHUB }}/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
  gateway:
    image: ${{ secrets.NICKNAME_GITHUB }}/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static:/static/
      - media:/app/media/
    ports:
      - 9000:80
